class SettingInfo{
    title:string
    carId:number
    makerId:number
    courseId:number
    abs:number
    powerSteering:number
    diffgear:number
    frontTirePressure:number
    rearTirePressure:number
    tireId:number
    airPressure:number
    gearFinal:number
    gearOne:number
    gearTwo:number
    gearThree:number
    gearFour:number
    gearFive:number
    stabiliserAgo:number
    stabiliserAfter:number
    maxRudderAngle:number
    ackermannAngle:number
    camberAgo:number
    camberAfter:number
    breakPower:number
    breakBallance:number
    carHigh:number
    offset:number
    hoilesize:number
    memo:number
}